[build]
builder = "NIXPACKS"
watchPatterns = ["backend/**"]

[deploy]
numReplicas = 1
startCommand = "cd backend && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "backend"
envVars = [
    { key = "NODE_ENV", value = "production" },
    { key = "PORT", value = "8000" }
] 