[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100

[nixpacks]
nodejs = "18"
workdir = "backend"

[phases.setup]
nixPkgs = ["nodejs", "npm"] 