services:
  - type: web
    name: trackfin-backend
    env: node
    rootDirectory: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000 